#**SECTION-A : Data Structures & Control Structures**

##**Exercise 1**

Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [ ]:
#Creating a list of Five integers.
list = [400,300,500,100,200]
print("Original list: ",list)

#append(): adds the element to the end of the list.
list.append(150)
print("append(): ",list)

#extend(): adds multiple elements to the end of the list.
list.extend([250,350,450])
print("extend() list: ",list)

#insert(): adds the element at a specified position in the list.
list.insert(2,550)
print("insterted 550 at the 2nd position")
print("insert() list: ",list)

#remove(): removes the specified value from the list.
list.remove(550)
print("removed 550 from the list")
print("remove() list: ",list)

#pop(): deletes the element from the list.
popped = list.pop()
print("Popped element: ",popped)
print("pop() list: ",list)

#sort(): Arranges the elements of the list in the ascending order.
list.sort()
print("sort() list: ",list)

#reverse(): Reverse the order of the elements in the list.
list.reverse()
print("reverse() list: ",list)

#index(): Removes and returns the element from the list.
index = list.index(350)
print("Index of 350: ",index)

#count(): Shows the number of elements of the given value.
count = list.count(200)
print("Count of 200: ",count)

#clear(): Removes all the elements from the list.
list.clear()
print("clear() list: ",list)

Original list:  [400, 300, 500, 100, 200]
append():  [400, 300, 500, 100, 200, 150]
extend() list:  [400, 300, 500, 100, 200, 150, 250, 350, 450]
insterted 550 at the 2nd position
insert() list:  [400, 300, 550, 500, 100, 200, 150, 250, 350, 450]
removed 550 from the list
remove() list:  [400, 300, 500, 100, 200, 150, 250, 350, 450]
Popped element:  450
pop() list:  [400, 300, 500, 100, 200, 150, 250, 350]
sort() list:  [100, 150, 200, 250, 300, 350, 400, 500]
reverse() list:  [500, 400, 350, 300, 250, 200, 150, 100]
Index of 350:  2
Count of 200:  1
clear() list:  []


##**Exercise 2**

Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [ ]:
#Creating a tuple() of three student names.
tup = ("Puneeth","Dilip","Sravani")

In [ ]:
tup

('Puneeth', 'Dilip', 'Sravani')

In [ ]:
#tuple elements cannot be changed as it is "Immutable"
try :
  tup[3] = "Sravya"
except :
  print("Tuples are immutable")

Tuples are immutable


##**Exercise 3**

Create a set of integers with some duplicate values. Print the set and explain the output.

In [ ]:
#Creating a set of integers with duplicate values.
set = {60,30,50,20,30,80,10,50,90,50}

In [ ]:
#set{} automatically arranges the values in the ascending order and returns by eliminating the duplicate elements.
set

{10, 20, 30, 50, 60, 80, 90}

##**Exercise 4**

Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [ ]:
#Creating a dictionary with 'name', 'age' and 'city'.
dict = {'Name':'Puneeth','Age':20,'City':'Hyderabad'}
print("Original dictionary: ",dict)

#Updating the age in the dictionary.
dict['Age'] = 26
print("Updated age: ",dict)

Original dictionary:  {'Name': 'Puneeth', 'Age': 20, 'City': 'Hyderabad'}
Updated age:  {'Name': 'Puneeth', 'Age': 26, 'City': 'Hyderabad'}


##**Exercise 5**

Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [ ]:
Age = int(input("Enter your age: "))
if Age >= 18:
  print("You are eligible to vote")
else :
  print("You are not eligible to vote")

Enter your age: 27
You are eligible to vote


##**Exercise 6**

Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'

In [ ]:
#Creating the code for Grading of the students with respect to the obtained marks.
marks = int(input("Enter your marks: "))
if marks >= 90 and marks <= 100:
  print("Your grade is A")
elif marks >=  75 and marks <= 89:
  print("Your grade is B")
elif marks >= 50 and marks <= 74:
  print("Your grade is C")
elif marks >= 0 and marks <=49:
  print("You are Fail")
else :
  print("Enter the marks between 0 to 100")

Enter your marks: 95
Your grade is A


##**Exercise 7**

Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [ ]:
num = int(input("Enter a number: "))

if num > 0:
  if num % 2 == 0:
    print("The entered number is Positive and Even.")
  else :
    print("The entered number is Positive but not Even.")
elif num == 0:
  print("The entered number is Zero.")
else :
  print("The entered number is Negative.")

Enter a number: 69
The entered number is Positive but not Even.


#**SECTION-B: NumPy**

##**Exercise 8**

Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10

In [ ]:
#Creating a Scalar using np.array(5):
import numpy as np
array1 = np.array(5)
print("Scalar: ",array1)

Scalar:  5


In [ ]:
#Creating a 1D array with values 1 ot 5:
array2 = np.array([1,2,3,4,5])
print("1D array: ")
print(array2)

1D array: 
[1 2 3 4 5]


In [ ]:
#Creating a 2D array (2x3) with values from 10 to 60 in steps of 10
array3 = np.arange(10,70,10).reshape(2,3)
print("2D array: ",)
print(array3)

2D array: 
[[10 20 30]
 [40 50 60]]


##**Exercise 9**

Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [ ]:
#Creating the 4x4 NumPy array of random integers between 0 and 100.
array4 = np.random.randint(0,100,size=(4,4))
print("4x4 NumPy array of random integers between 0 and 100: ")
print(array4)

4x4 NumPy array of random integers between 0 and 100: 
[[15 69  2 48]
 [60 62 78 60]
 [42 12 39 63]
 [54 44 67 25]]


##**Exercise 10**

Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [ ]:
#Creating a 2D NumPy array of (3x3):
data = np.array([[10,20,30],[40,50,60],[70,80,90]])
print("2D NumPy array of (3x3): ")
print(data)

#Converting the array into DataFrame with column names as 'A','B','C'.
import pandas as pd
df = pd.DataFrame(data,columns=['A','B','C'])
print("DataFrame: ")
print(df)

2D NumPy array of (3x3): 
[[10 20 30]
 [40 50 60]
 [70 80 90]]
DataFrame: 
    A   B   C
0  10  20  30
1  40  50  60
2  70  80  90


#**SECTION-C: Exploring Pandas**

##**Exercise 11**

Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows.

In [ ]:
#Creating a manual DataFrame of 10 rows:
data2 = {'Name':['Puneeth','Dilip','Subash','Sainath','Aniketh','Vittal','Prudhvi','Subash','Praneeth','Puneeth'],
         'Age':['26','25','29','27','30','25','20','29','17','26'],
         'City':['Hyderabad','Lahore','Chennai','Mumbai','Bangalore','Pune','Vizag','Chennai','Hyderabad','Hyderabad'],
         'Salary':[18000,np.nan,22000,25000,80000,19000,30000,22000,np.nan,18000]}
df2  = pd.DataFrame(data2)
df2

Name Age       City   Salary
0   Puneeth  26  Hyderabad  18000.0
1     Dilip  25     Lahore      NaN
2    Subash  29    Chennai  22000.0
3   Sainath  27     Mumbai  25000.0
4   Aniketh  30  Bangalore  80000.0
5    Vittal  25       Pune  19000.0
6   Prudhvi  20      Vizag  30000.0
7    Subash  29    Chennai  22000.0
8  Praneeth  17  Hyderabad      NaN
9   Puneeth  26  Hyderabad  18000.0

In [ ]:
#Using info(), and describe():

print("DataFrame Information: ")
print(df2.info())

print("DataFrame Description: ")
print(df2.describe())

DataFrame Information: 
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     object 
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), object(3)
memory usage: 452.0+ bytes
None
DataFrame Description: 
             Salary
count      8.000000
mean   29250.000000
std    20899.418994
min    18000.000000
25%    18750.000000
50%    22000.000000
75%    26250.000000
max    80000.000000


In [ ]:
#Selecting 'Name' and 'City' colunmns:
print("Selecting Name and City columns: ")
print(df2[['Name','City']])

Selecting Name and City columns: 
       Name       City
0   Puneeth  Hyderabad
1     Dilip     Lahore
2    Subash    Chennai
3   Sainath     Mumbai
4   Aniketh  Bangalore
5    Vittal       Pune
6   Prudhvi      Vizag
7    Subash    Chennai
8  Praneeth  Hyderabad
9   Puneeth  Hyderabad


In [ ]:
#Dropping 'City' column:
df3 = df2.drop(columns=['City'])
print("DataFrame after dropping 'City' column: ")
print(df3)

DataFrame after dropping 'City' column: 
       Name Age   Salary
0   Puneeth  26  18000.0
1     Dilip  25      NaN
2    Subash  29  22000.0
3   Sainath  27  25000.0
4   Aniketh  30  80000.0
5    Vittal  25  19000.0
6   Prudhvi  20  30000.0
7    Subash  29  22000.0
8  Praneeth  17      NaN
9   Puneeth  26  18000.0


In [ ]:
#Removing duplicate rows:
df3 = df3.drop_duplicates()
print("DataFrame after removing duplicate rows: ")
print(df3)

DataFrame after removing duplicate rows: 
       Name Age   Salary
0   Puneeth  26  18000.0
1     Dilip  25      NaN
2    Subash  29  22000.0
3   Sainath  27  25000.0
4   Aniketh  30  80000.0
5    Vittal  25  19000.0
6   Prudhvi  20  30000.0
8  Praneeth  17      NaN


In [ ]:
#Filling missing values in 'Salary' column with mean:
mean = df3['Salary'].mean()
df3['Salary'].fillna(mean)
print("DataFrame after filling missing values in 'Salary' column with mean: ")
print(df3)


DataFrame after filling missing values in 'Salary' column with mean: 
       Name Age        Salary
0   Puneeth  26  18000.000000
1     Dilip  25  32333.333333
2    Subash  29  22000.000000
3   Sainath  27  25000.000000
4   Aniketh  30  80000.000000
5    Vittal  25  19000.000000
6   Prudhvi  20  30000.000000
8  Praneeth  17  32333.333333
